import { Router, type IRouter } from "express";
import { superAdminFinancialMask } from "../lib/financialMask";
import healthRouter from "./health";
import authRouter from "./auth";
import replitAuthRouter from "./replitAuth";
import tenantsRouter from "./tenants";
import branchesRouter from "./branches";
import usersRouter from "./users";
import clientsRouter from "./clients";
import fundProductsRouter from "./fundProducts";
import loanRequestsRouter from "./loanRequests";
import loansRouter from "./loans";
import glRouter from "./glAccounts";
import dashboardRouter from "./dashboard";
import installmentsRouter from "./installments";
import paymentsRouter from "./payments";
import salesAgentsRouter from "./salesAgents";
import commissionsRouter from "./commissions";
import calculatorRouter from "./calculator";
import riskRouter from "./risk";
import reportsRouter from "./reports";
import blacklistsRouter from "./blacklists";
import iscoreRouter from "./iscore";
import approvalsRouter from "./approvals";
import portfolioTransfersRouter from "./portfolioTransfers";
import documentsRouter from "./documents";
import epaymentsRouter from "./epayments";
import expensesRouter from "./expenses";
import workflowsRouter from "./workflows";
import branchRequestsRouter from "./branchRequests";
import offloadingRouter from "./offloading";
import creditLimitsRouter from "./creditLimits";
import chequesRouter from "./cheques";
import wireTransfersRouter from "./wireTransfers";
import cashSettlementsRouter from "./cashSettlements";
import notificationsRouter from "./notifications";
import bulkOperationsRouter from "./bulkOperations";
import collectionActivitiesRouter from "./collectionActivities";
import guaranteesRouter from "./guarantees";
import bankFacilitiesRouter from "./bankFacilities";
import auditLogsRouter from "./auditLogs";
import clientGroupsRouter from "./clientGroups";
import dailyClosingRouter from "./dailyClosing";
import periodicClosingRouter from "./periodicClosing";
import settingsRouter from "./settings";
import subscriptionsRouter from "./subscriptions";
import holidaysRouter from "./holidays";
import financialStatementsRouter from "./financialStatements";
import systemAnnouncementsRouter from "./systemAnnouncements";
import bankReconciliationRouter from "./bankReconciliation";
import complianceRouter from "./compliance";
import systemRouter from "./system";
import chatbotRouter from "./chatbot";
import savingsRouter from "./savings";
import collateralsRouter from "./collaterals";
import branchCashTransfersRouter from "./branchCashTransfers";
import dataExportRouter from "./dataExport";
import fraReportsRouter from "./fraReports";
import twoFactorRouter from "./twoFactor";
import emailNotificationsRouter from "./emailNotifications";
import loanAgingRouter from "./loanAging";
import smsNotificationsRouter from "./smsNotifications";
import webhooksRouter from "./webhooks";
import officerCheckinsRouter from "./officerCheckins";
import clientPortalRouter from "./clientPortal";
import portfolioAnalyticsRouter from "./portfolioAnalytics";
import bulkAdjustmentsRouter from "./bulkAdjustments";
import userNotificationsRouter from "./userNotifications";
import fixedAssetsRouter from "./fixedAssets";
import vendorsRouter from "./vendors";
import employeesRouter from "./employees";
import budgetsRouter from "./budgets";
import costCentersRouter from "./costCenters";
import recurringJournalsRouter from "./recurringJournals";
import taxConfigRouter from "./taxConfig";
import nidaRouter from "./nida";
import amlScreeningRouter from "./amlScreening";
import pdplRouter from "./pdpl";
import tenantDeletionRouter from "./tenantDeletion";
import ifrs9Router from "./ifrs9";
import aiRiskEngineRouter from "./aiRiskEngine";
import etaRouter from "./eta";
import ekycRouter from "./ekyc";
import insuranceRouter from "./insurance";
import agentBankingRouter from "./agentBanking";
import loanRestructuringRouter from "./loanRestructuring";
import mobileWalletRouter from "./mobileWallet";
import whatsappRouter from "./whatsapp";
import ocrDocumentsRouter from "./ocrDocuments";
import aiCollectionRouter from "./aiCollection";
import dynamicPricingRouter from "./dynamicPricing";
import cashFlowPredictionRouter from "./cashFlowPrediction";
import stressTestingRouter from "./stressTesting";
import churnPredictionRouter from "./churnPrediction";
import nlpReportingRouter from "./nlpReporting";
import attendanceRouter from "./attendance";
import endOfServiceRouter from "./endOfService";
import taxReportsRouter from "./taxReports";
import platformAlertsRouter from "./platformAlerts";
import tenantBillingRouter from "./tenantBilling";
import tenantComparisonRouter from "./tenantComparison";
import superAdminDeleteRouter from "./superAdminDelete";
import impersonationRouter from "./impersonation";

const router: IRouter = Router();

router.use(superAdminFinancialMask);
router.use(healthRouter);
router.use(replitAuthRouter);
router.use("/auth", authRouter);
router.use("/tenants", tenantsRouter);
router.use("/branches", branchesRouter);
router.use("/users", usersRouter);
router.use("/clients", clientsRouter);
router.use("/fund-products", fundProductsRouter);
router.use("/loan-requests", loanRequestsRouter);
router.use("/loans", loansRouter);
router.use("/", glRouter);
router.use("/dashboard", dashboardRouter);
router.use("/settings", settingsRouter);
router.use("/installments", installmentsRouter);
router.use("/payments", paymentsRouter);
router.use("/sales-agents", salesAgentsRouter);
router.use("/", commissionsRouter);
router.use("/calculator", calculatorRouter);
router.use("/", riskRouter);
router.use("/reports", reportsRouter);
router.use("/blacklists", blacklistsRouter);
router.use("/iscore", iscoreRouter);
router.use("/approval-requests", approvalsRouter);
router.use("/portfolio-transfers", portfolioTransfersRouter);
router.use("/documents", documentsRouter);
router.use("/epayments", epaymentsRouter);
router.use("/expenses", expensesRouter);
router.use("/custom-workflows", workflowsRouter);
router.use("/branch-requests", branchRequestsRouter);
router.use("/offloading", offloadingRouter);
router.use("/credit-limits", creditLimitsRouter);
router.use("/cheques", chequesRouter);
router.use("/wire-transfers", wireTransfersRouter);
router.use("/cash-settlements", cashSettlementsRouter);
router.use("/notifications", notificationsRouter);
router.use("/bulk-operations", bulkOperationsRouter);
router.use("/collection-activities", collectionActivitiesRouter);
router.use("/guarantees", guaranteesRouter);
router.use("/bank-facilities", bankFacilitiesRouter);
router.use("/audit-logs", auditLogsRouter);
router.use("/client-groups", clientGroupsRouter);
router.use("/daily-closing", dailyClosingRouter);
router.use("/periodic-closing", periodicClosingRouter);
router.use("/subscriptions", subscriptionsRouter);
router.use("/holidays", holidaysRouter);
router.use("/financial-statements", financialStatementsRouter);
router.use("/announcements", systemAnnouncementsRouter);
router.use("/bank-reconciliation", bankReconciliationRouter);
router.use("/compliance", complianceRouter);
router.use("/system", systemRouter);
router.use("/chatbot", chatbotRouter);
router.use("/savings", savingsRouter);
router.use("/collaterals", collateralsRouter);
router.use("/branch-cash-transfers", branchCashTransfersRouter);
router.use("/data-export", dataExportRouter);
router.use("/fra-reports", fraReportsRouter);
router.use("/2fa", twoFactorRouter);
router.use("/email-notifications", emailNotificationsRouter);
router.use("/loan-aging", loanAgingRouter);
router.use("/sms-notifications", smsNotificationsRouter);
router.use("/webhooks", webhooksRouter);
router.use("/officer-checkins", officerCheckinsRouter);
router.use("/client-portal", clientPortalRouter);
router.use("/portfolio-analytics", portfolioAnalyticsRouter);
router.use("/bulk-adjustments", bulkAdjustmentsRouter);
router.use("/user-notifications", userNotificationsRouter);
router.use("/fixed-assets", fixedAssetsRouter);
router.use("/vendors", vendorsRouter);
router.use("/employees", employeesRouter);
router.use("/budgets", budgetsRouter);
router.use("/cost-centers", costCentersRouter);
router.use("/recurring-journals", recurringJournalsRouter);
router.use("/tax-config", taxConfigRouter);
router.use("/nida", nidaRouter);
router.use("/aml", amlScreeningRouter);
router.use("/pdpl", pdplRouter);
router.use("/tenant-deletion", tenantDeletionRouter);
router.use("/ifrs9", ifrs9Router);
router.use("/ai-risk", aiRiskEngineRouter);
router.use("/eta", etaRouter);
router.use("/ekyc", ekycRouter);
router.use("/insurance", insuranceRouter);
router.use("/agent-banking", agentBankingRouter);
router.use("/loan-restructuring", loanRestructuringRouter);
router.use("/mobile-wallet", mobileWalletRouter);
router.use("/whatsapp", whatsappRouter);
router.use("/ocr", ocrDocumentsRouter);
router.use("/ai-collection", aiCollectionRouter);
router.use("/dynamic-pricing", dynamicPricingRouter);
router.use("/cash-flow-prediction", cashFlowPredictionRouter);
router.use("/stress-testing", stressTestingRouter);
router.use("/churn-prediction", churnPredictionRouter);
router.use("/nlp-reporting", nlpReportingRouter);
router.use("/attendance", attendanceRouter);
router.use("/end-of-service", endOfServiceRouter);
router.use("/tax-reports", taxReportsRouter);
router.use("/platform-alerts", platformAlertsRouter);
router.use("/tenant-billing", tenantBillingRouter);
router.use("/tenant-comparison", tenantComparisonRouter);
router.use("/super-admin/delete", superAdminDeleteRouter);
router.use("/admin/impersonate", impersonationRouter);

export default router;
